### ISSUE TITLE
Examples does not work, probably some protocol changes

### ISSUE THREAD

**Issue by arcaine2** [JuniorJPDJ/pyChomikBox#11]
When trying to test a list.py i always get:

```
Traceback (most recent call last):
  File "./list.py", line 31, in <module>
    files.extend(f.files_list(only_downloadable=True))
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 352, in files_list
    resp = self._send_action('Download', a_data)
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 275, in _send_action
    raise SendActionFailedException(action, resp['a:errorMessage'])
ChomikBox.ChomikBox.SendActionFailedException: Download: failed : requested file(s) not available
```
When trying example.py:

```
[21:18:46][DEBUG]: ChomikBox.Chomik.USERNAME | Sending action: "Auth"
[21:18:46][DEBUG]: urllib3.connectionpool | Starting new HTTPS connection (1): box.chomikuj.pl:443
[21:18:47][DEBUG]: urllib3.connectionpool | https://box.chomikuj.pl:443 "POST /services/ChomikBoxService.svc HTTP/1.1" 200 279
[21:18:47][DEBUG]: ChomikBox.Chomik.USERNAME | Action sent: "Auth"
[21:18:47][DEBUG]: ChomikBox.Chomik.USERNAME| Logged in with token d3afa824-b61e-4de5-b31e-c26f2b87d6a7
[21:18:47][DEBUG]: urllib3.connectionpool | Starting new HTTPS connection (1): chomikuj.pl:443
[21:18:47][DEBUG]: urllib3.connectionpool | https://chomikuj.pl:443 "GET /chomik/chomikbox/LoginFromBox?t=d3afa824-b61e-4de5-b31e-c26f2b87d6a7&returnUrl=USERNAME HTTP/1.1" 302 126
[21:18:48][DEBUG]: urllib3.connectionpool | https://chomikuj.pl:443 "GET /USERNAME HTTP/1.1" 200 13917
[21:18:48][DEBUG]: ChomikBox.Chomik.USERNAME | Loading folders from folder 0
[21:18:48][DEBUG]: ChomikBox.Chomik.USERNAME | Sending action: "Folders"
[21:18:48][DEBUG]: urllib3.connectionpool | https://box.chomikuj.pl:443 "POST /services/ChomikBoxService.svc HTTP/1.1" 200 685
[21:18:48][DEBUG]: ChomikBox.Chomik.USERNAME | Action sent: "Folders"
[21:18:48][DEBUG]: ChomikBox.Chomik.USERNAME | Loading files from folder 0
[21:18:48][DEBUG]: ChomikBox.Chomik.USERNAME | Sending action: "Download"
[21:18:48][DEBUG]: urllib3.connectionpool | https://box.chomikuj.pl:443 "POST /services/ChomikBoxService.svc HTTP/1.1" 200 286
Traceback (most recent call last):
  File "./myChomikuj.py", line 32, in <module>
    fold = c.get('upload')
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 201, in get
    found = self.get_file(name, case_sensitive)
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 188, in get_file
    for f in self.files_list():
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 352, in files_list
    resp = self._send_action('Download', a_data)
  File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 275, in _send_action
    raise SendActionFailedException(action, resp['a:errorMessage'])
ChomikBox.ChomikBox.SendActionFailedException: Download: failed : requested file(s) not available

```

Of course i provided valid credentials and this seems to work. Tested on Python 3.7.0.

**Comment by JuniorJPDJ** [comment]
I'll take a look, thank you

**Comment by arcaine2** [comment]
Any hope to get this sorted out soon(ish)? I planned to use this to update my uploads on chomikuj. Original client is still crap and creates new files and directories instead of just uploading the changes what makes whole process a huge mess.

**Comment by JuniorJPDJ** [comment]
I'll probably have no time in next 2 weeks :/
Sorry.
You can try to hook proxy sniffer like burp suite to original client and try to fix it yourself :D 
I'll probably be able to provide help (from phone).

**Comment by arcaine2** [comment]
I'll probably wait. I did a bit of digging back then and there seemed to be a problem with listing files. I can see that directories are listed, at least some of them - from root directory only, then it stops working.

I tried it again today - no changes done to the script but now the directories listing goes on. Maybe it was a bug on Chomikuj side, lasting 3-4 days after all, maybe i messed something up.

For sure examples are a bit bugged. In example.py you have:
`fold = c.get('upload')`
This is executed right after logging in so this seems it tries download "upload" file that's not there yet.

This on the other hand:
`uploader = fold.upload_file(open(args.upload_file, 'rb'), name, callback.progress_callback)`
Should look like this?:
`uploader = c.upload_file(open(args.upload_file, 'rb'), name, callback.progress_callback)`

After i changed it, i see SSL version number error:

> 
> [22:11:58][DEBUG]: ChomikBox.Chomik.USERNAME| Error HTTPSConnectionPool(host='s6962.chomikuj.pl', port=8084): Max retries exceeded with url: /file/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)'))) occurred during upload of file "test.txt"
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
>     self._validate_conn(conn)
>   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
>     conn.connect()
>   File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
>     ssl_context=context)
>   File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 342, in ssl_wrap_socket
>     return context.wrap_socket(sock, server_hostname=server_hostname)
>   File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
>     session=session
>   File "/usr/lib/python3.7/ssl.py", line 853, in _create
>     self.do_handshake()
>   File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='s6962.chomikuj.pl', port=8084): Max retries exceeded with url: /file/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)')))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "example.py", line 67, in <module>
>     uploader.start()
>   File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 661, in start
>     raise e
>   File "/usr/lib/python3.7/site-packages/ChomikBox/ChomikBox.py", line 644, in start
>     resp = self.chomik.sess.post('http{}://{server}/file/'.format('s' if self.chomik.ssl else '', server=self.server), data=monitor, headers=headers)
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 572, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
>     raise SSLError(e, request=request)
> requests.exceptions.SSLError: HTTPSConnectionPool(host='s6962.chomikuj.pl', port=8084): Max retries exceeded with url: /file/ (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1051)')))

Uploading desn't work, at least for me, due to that problem.

hash.py seems to work and creates sha1 hashes for files and directories once i changed skip_hashed to False. Downloading files should work as well if hashes are created.

**Comment by Pitirus** [comment]
Calling the `_send_action('Download', a_data)` in line 352 of `ChomikBox.py` file seems to invoke `ChomikBox.ChomikBox.SendActionFailedException` when there are no files in given folder. I don't know how to list all available actions (maybe there is a better action than `'Download'`) but wrapping this call with `try-except` seems to do the job.
So instead of:

    resp = self._send_action('Download', a_data)

I think there should be:

    try:
      resp = self._send_action('Download', a_data)
    except SendActionFailedException:  # there are no files in the folder
      return []

**Comment by arcaine2** [comment]
This helps to get rid of that initial issue and listing files and directories works fine, even nested one. Uploading still doesn't work for me, same SSL error i pasted above.

**Comment by JuniorJPDJ** [comment]
@Pitirus the `Download` action was a workaround which I've found in 
@Grycek 's ChomikDownloader.
Haven't figured out other idea to list files.. And I didn't either figure out how to list available actions.
Thank you for debugging.
tbh I forgot about this issue
SSL version is bcs of server settings, we will not be able to do anything.
I'll check it today evening.

**Comment by arcaine2** [comment]
Any new development regarding SSL issue?

**Comment by JuniorJPDJ** [comment]
I fixed the initial issue.

**Comment by JuniorJPDJ** [comment]
I turned off SSL for file upload (just file transfer - passwords, metadata, negotiations are still through SSL).
I can reproduce issue but don't know other fix ATM
